Asp.ErpFidelitas.General.v2/Entities/MovementAccountReceivable.cs
using System;

namespace Asp.ErpFidelitas.General.v2.Entities
{
	
     
    public class MovementAccountReceivable
    {
        public int CompanyId { get; set; }
        public long AccountsReceivableId { get; set; }
        public long? PersonId { get; set; }
        public Nullable<short> CurrencyId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public short DocumentTypeId { get; set; }
    } 
}

Asp.ErpFidelitas.General.v2/Controllers/MovementAccountReceivableController.cs
using Asp.ErpFidelitas.General.v2.App_Start;
using Asp.ErpFidelitas.General.v2.Entities;
using Asp.ErpFidelitas.General.v2.Utilities;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Asp.ErpFidelitas.General.v2.Controllers
{
    [AutorizarFiltro]
    public class MovementAccountReceivableController : BaseController
    {
        MovementAccountReceivable movAccRec;
        List<MovementAccountReceivable> movAccReceivables;
        Response responseClient;

        const string UrlActionPathAllPersonas = "https://localhost:44331/General/Persons/ObtenerTodas";
        const string UrlActionPathAllCurrencys = "https://localhost:44331/General/Currencys/ObtenerTodas";
        const string UrlActionPathAllTiposDoc = "https://localhost:44331/General/DocumentTypes/ObtenerTodas";

        const string UrlActionPathDetails = "https://localhost:44331/General/MovementsAccountsReceivable/ObtenerUno?id={0}";
        const string UrlActionPathList = "https://localhost:44331/General/MovementsAccountsReceivable/ObtenerTodas";
        const string UrlActionPathInsertOne = "https://localhost:44331/General/MovementsAccountsReceivable/CrearUno";
        const string UrlActionPathUpdate = "https://localhost:44331/General/MovementsAccountsReceivable/ActualizarUno";
        const string UrlActionPathDelete = "https://localhost:44331/General/MovementsAccountsReceivable/BorrarUno?id={0}";

        // GET: MovementAccountReceivable
        public async Task<ActionResult> Index()
        {
            movAccReceivables = new List<MovementAccountReceivable>();
            responseClient = new Response();

            try
            {
                using (var client = new HttpClient())
                {
                    HttpResponseMessage response = await client.GetAsync(UrlActionPathList);
                    if (response.IsSuccessStatusCode)
                    {
                        var str = await response.Content.ReadAsStringAsync();
                        responseClient = JsonConvert.DeserializeObject<Response>(str);
                    }
                    if (responseClient.Success)
                    {
                        movAccReceivables = JsonConvert.DeserializeObject<List<MovementAccountReceivable>>(responseClient.Value.ToString());
                    }
                }
            }
            catch (Exception error)
            {
                ViewBag.ErrorInfo = ERRORMESSAGE;
                ViewBag.ErrorMessage = error.Message;
                ViewBag.InnerException = error.InnerException;
                ViewBag.StackTrace = error.StackTrace;
                return View("Error");
            }
            return View(movAccReceivables);
        }

        // GET: MovementAccountReceivable/Details/5
        public async Task<ActionResult> Details(int id)
        {
            movAccRec = new MovementAccountReceivable();
            responseClient = new Response();

            try
            {
                using (var client = new HttpClient())
                {
                    HttpResponseMessage response = await client.GetAsync(string.Format(UrlActionPathDetails, id));
                    if (response.IsSuccessStatusCode)
                    {
                        var str = await response.Content.ReadAsStringAsync();
                        responseClient = JsonConvert.DeserializeObject<Response>(str);
                    }
                    if (responseClient.Success)
                    {
                        movAccRec = JsonConvert.DeserializeObject<MovementAccountReceivable>(responseClient.Value.ToString());
                    }
                }
            }
            catch (Exception error)
            {
                ViewBag.ErrorInfo = ERRORMESSAGE;
                ViewBag.ErrorMessage = error.Message;
                ViewBag.InnerException = error.InnerException;
                ViewBag.StackTrace = error.StackTrace;
                return View("Error");
            }
            return View(movAccRec);

        }

        // GET: MovementAccountReceivable/Create
        public async Task<ActionResult> Create()
        {

            ViewBag.ListaTiposDocumento = new List<SelectListItem>();
            ViewBag.ListaMonedas = new List<SelectListItem>();
            ViewBag.ListaPersonas = new List<SelectListItem>();

            ViewBag.ListaTiposDocumento = await ObtenerComboTiposDocumento();
            ViewBag.ListaMonedas = await ObtenerComboMonedas();
            ViewBag.ListaPersonas = await ObtenerComboPersonasAsync();
            //TempData["MensajesExito"] = EstadoOperacion ? "Operacion realizada exitosamente!" : "";

            return View();
        }

        private async Task<List<SelectListItem>> ObtenerComboPersonasAsync()
        {
            List<SelectListItem> keyValuePairs = new List<SelectListItem>();

            List<Person> persons = new List<Person>();
            try
            {
                using (var client = new HttpClient())
                {
                    HttpResponseMessage response = await client.GetAsync(string.Format(UrlActionPathAllPersonas));
                    if (response.IsSuccessStatusCode)
                    {
                        var str = await response.Content.ReadAsStringAsync();
                        responseClient = JsonConvert.DeserializeObject<Response>(str);
                    }
                    if (responseClient.Success)
                    {
                        persons = JsonConvert.DeserializeObject<List<Person>>(responseClient.Value.ToString());
                    }
                    foreach (var item in persons)
                    {

                        keyValuePairs.Add(new SelectListItem { Text = $"{item.FirstName} {item.LastName}", Value = item.PersonId.ToString() });
                    }
                }
            }
            catch (Exception error)
            {
                ViewBag.ErrorInfo = ERRORMESSAGE;
                ViewBag.ErrorMessage = error.Message;
                ViewBag.InnerException = error.InnerException;
                ViewBag.StackTrace = error.StackTrace;

            }

            return keyValuePairs;
        }
        private async Task<List<SelectListItem>> ObtenerComboMonedas()
        {
            List<SelectListItem> keyValuePairs = new List<SelectListItem>();

            List<Currency> products = new List<Currency>();
            try
            {
                using (var client = new HttpClient())
                {
                    HttpResponseMessage response = await client.GetAsync(string.Format(UrlActionPathAllCurrencys));
                    if (response.IsSuccessStatusCode)
                    {
                        var str = await response.Content.ReadAsStringAsync();
                        responseClient = JsonConvert.DeserializeObject<Response>(str);
                    }
                    if (responseClient.Success)
                    {
                        products = JsonConvert.DeserializeObject<List<Currency>>(responseClient.Value.ToString());
                    }
                    foreach (var item in products)
                    {

                        keyValuePairs.Add(new SelectListItem { Text = item.Name, Value = item.CurrencyId.ToString() });
                    }
                }
            }
            catch (Exception error)
            {
                ViewBag.ErrorInfo = ERRORMESSAGE;
                ViewBag.ErrorMessage = error.Message;
                ViewBag.InnerException = error.InnerException;
                ViewBag.StackTrace = error.StackTrace;

            }

            return keyValuePairs;
        }
        private async Task<List<SelectListItem>> ObtenerComboTiposDocumento()
        {
            List<SelectListItem> keyValuePairs = new List<SelectListItem>();

            List<DocumentType> products = new List<DocumentType>();
            try
            {
                using (var client = new HttpClient())
                {
                    HttpResponseMessage response = await client.GetAsync(string.Format(UrlActionPathAllTiposDoc));
                    if (response.IsSuccessStatusCode)
                    {
                        var str = await response.Content.ReadAsStringAsync();
                        responseClient = JsonConvert.DeserializeObject<Response>(str);
                    }
                    if (responseClient.Success)
                    {
                        products = JsonConvert.DeserializeObject<List<DocumentType>>(responseClient.Value.ToString());
                    }
                    foreach (var item in products.Where(d => d.Name.Contains("CXC")))
                    {

                        keyValuePairs.Add(new SelectListItem { Text = item.Name, Value = item.DocumentTypeId.ToString() });
                    }
                }
            }
            catch (Exception error)
            {
                ViewBag.ErrorInfo = ERRORMESSAGE;
                ViewBag.ErrorMessage = error.Message;
                ViewBag.InnerException = error.InnerException;
                ViewBag.StackTrace = error.StackTrace;

            }

            return keyValuePairs;
        }


        // POST: MovementAccountReceivable/Create
        [HttpPost]
        public async Task<ActionResult> Create(MovementDebtToPay collection, long[] PersonaId, short[] TipoDocumentId, decimal[] Monto, short[] Moneda)
        {

            //fila = '<tr class="odd">';
            //fila = fila + '<td class="sorting_1"> <input type="text" class="form-control-plaintext" name="PersonaId" value="' + $("#ddlPersona").val() + '"></td>';
            //fila = fila + '<td > <input class="form-control-plaintext" type="text" name="TipoDocumentId" value="' + $("#ddlTipoDocumento").val() + '"></td>';

Asp.ErpFidelitas.General.v2/Views/MovementAccountReceivable/Create.cshtml
@model Asp.ErpFidelitas.General.v2.Entities.MovementAccountReceivable

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@*combo PersonId
    CurrencyId
    Amount
    DocumentTypeId*@



@*<div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>*@

@Html.Hidden("txtMessage", TempData["MensajesExito"], htmlAttributes: new { id = "txtMessage" })

<!-- Account details card-->
<div class="card mb-12">
    <div class="card-header">Cuentas por cobrar</div>
    <div class="card-body">
        <form>
            <!-- Form Group (username)-->

            <div class="row gx-3 mb-12">
                <div class="col-md-6">
                    <label class="small mb-1">Tipo Documento</label>
                    <br>
                    <select id="dlTipoDocumento" class="dropdown" aria-label="Default select example">
                        <option selected="">Seleccione un Tipo Documento:</option>
                        @foreach (var item in ViewBag.ListaTiposDocumento as List<SelectListItem>)
                        {
                            <option value="@item.Value">@item.Text</option>
                        }
                    </select>
                </div>

                <div class="col-md-6">
                    <label class="small mb-1">Cliente</label>
                    <br>
                    @*@Html.DropDownListFor(m => m.ProductId, ViewBag.ListaArticulos as List<SelectListItem>, new { @class = "form-control" })*@
                    <select id="ddlPersona" class="form-select" aria-label="Default select example">
                        <option>Seleccione el proveedor:</option>
                        @foreach (var item in ViewBag.ListaPersonas as List<SelectListItem>)
                        {
                            <option value="@item.Value">@item.Text</option>

                        }
                    </select>
                </div>


            </div>
            <hr>
            <!-- Form Row-->
            <div class="row gx-3 mb-12">
                <div class="col-md-12">
                    <label class="small mb-3" for="txtMonto">Monto</label>
                    <br>
                    <input class="form-control" id="txtMonto" type="number" placeholder="999,999.99" value="1">
                </div>
                <!-- Form Group (last name)-->
            </div>
            <hr>
            <div class="row gx-3 mb-12">
                <div class="col-md-6">
                    <label class="small mb-3">Moneda</label>
                    <br>
                    <select id="ddlMoneda" class="form-select" aria-label="Default select example">
                        <option selected="" disabled="">Seleccione una:</option>
                        @foreach (var item in ViewBag.ListaMonedas as List<SelectListItem>)
                        {
                            <option value="@item.Value">@item.Text</option>

                        }
                    </select>


                </div>
            </div>
            <br>
            <!-- Save changes button-->
            <button class="btn btn-primary" type="button" onclick="userOne.AddMovimientoCXP()">Agregar </button>
        </form>
    </div>
</div>

@using (Html.BeginForm("Create", "MovementAccountReceivable", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Movimientos</h6>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar"
                       class="btn btn-primary btn-block">
                @*<button asp-action type="submit" value="Create" class="btn btn-secondary" />*@
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                    <div class="row"><div class="col-sm-12 col-md-6"><div class="dataTables_length" id="dataTable_length"><label>Show <select name="dataTable_length" aria-controls="dataTable" class="custom-select custom-select-sm form-control form-control-sm"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> entries</label></div></div><div class="col-sm-12 col-md-6"><div id="dataTable_filter" class="dataTables_filter"><label>Search:<input type="search" class="form-control form-control-sm" placeholder="" aria-controls="dataTable"></label></div></div></div><div class="row">
                        <div class="col-sm-12">
                            <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                                <thead>
                                    <tr role="row">
                                        <th class="sorting sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1"
                                            aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 142px;">Cliente</th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1"
                                            aria-label="Position: activate to sort column ascending" style="width: 220px;">Tipo Documento</th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1"
                                            aria-label="Age: activate to sort column ascending" style="width: 42px;">Monto</th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1"
                                            aria-label="Start date: activate to sort column ascending" style="width: 94px;">Moneda</th>
                                </thead>
                                <tfoot>
                                    @*<tr>
                                        <th rowspan="1" colspan="1">Cliente</th>
                                        <th rowspan="1" colspan="1">Tipo Documento</th>
                                        <th rowspan="1" colspan="1">Monto</th>
                                        <th rowspan="1" colspan="1">Moneda</th>*@
                                </tfoot>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div><div class="row"><div class="col-sm-12 col-md-5"><div class="dataTables_info" id="dataTable_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries</div></div><div class="col-sm-12 col-md-7"><div class="dataTables_paginate paging_simple_numbers" id="dataTable_paginate"><ul class="pagination"><li class="paginate_button page-item previous disabled" id="dataTable_previous"><a href="#" aria-controls="dataTable" data-dt-idx="0" tabindex="0" class="page-link">Previous</a></li><li class="paginate_button page-item active"><a href="#" aria-controls="dataTable" data-dt-idx="1" tabindex="0" class="page-link">1</a></li><li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="2" tabindex="0" class="page-link">2</a></li><li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="3" tabindex="0" class="page-link">3</a></li><li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="4" tabindex="0" class="page-link">4</a></li><li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="5" tabindex="0" class="page-link">5</a></li><li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="6" tabindex="0" class="page-link">6</a></li><li class="paginate_button page-item next" id="dataTable_next"><a href="#" aria-controls="dataTable" data-dt-idx="7" tabindex="0" class="page-link">Next</a></li></ul></div></div></div>
                </div>
            </div>
        </div>
    </div>
}
 

Asp.ErpFidelitas.General.v2/Views/MovementAccountReceivable/Details.cshtml
@model Asp.ErpFidelitas.General.v2.Entities.MovementAccountReceivable

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>MovementAccountReceivable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CompanyId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccountsReceivableId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountsReceivableId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PersonId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PersonId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrencyId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrencyId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DocumentTypeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DocumentTypeId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Asp.ErpFidelitas.General.v2/Views/MovementAccountReceivable/Edit.cshtml
@model Asp.ErpFidelitas.General.v2.Entities.MovementAccountReceivable

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "MovementAccountReceivable", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MovementAccountReceivable</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CompanyId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccountsReceivableId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccountsReceivableId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccountsReceivableId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PersonId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PersonId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CurrencyId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CurrencyId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CurrencyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DocumentTypeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DocumentTypeId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DocumentTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Asp.ErpFidelitas.General.v2/Views/MovementAccountReceivable/Index.cshtml
@model IEnumerable<Asp.ErpFidelitas.General.v2.Entities.MovementAccountReceivable>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CompanyId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AccountsReceivableId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PersonId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CurrencyId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DocumentTypeId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CompanyId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AccountsReceivableId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PersonId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CurrencyId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Amount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DocumentTypeId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>