Asp.ErpFidelitas.General.v2/Entities/RolUsers.cs
using System;

namespace Asp.ErpFidelitas.General.v2.Entities

{

    public class RolUsers
    {
        public int RolId { get; set; }
        public string TypeRol { get; set; }
    } 
}

Asp.ErpFidelitas.General.v2/Controllers/RolUsersController.cs
using Asp.ErpFidelitas.General.v2.App_Start;
using Asp.ErpFidelitas.General.v2.Entities;
using Asp.ErpFidelitas.General.v2.Utilities;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Asp.ErpFidelitas.General.v2.Controllers
{
    [AutorizarFiltro]
    public class RolUsersController : BaseController
    {
        RolUsers rolUsuario;
        List<RolUsers> rolUsuarios;
        Response responseClient;
        const string UrlActionPathDetails = "https://localhost:44331/General/RolUsers/ObtenerUno?id={0}";
        const string UrlActionPathList = "https://localhost:44331/General/RolUsers/ObtenerTodas";
        const string UrlActionPathInsertOne = "https://localhost:44331/General/RolUsers/CrearUno";
        const string UrlActionPathUpdate = "https://localhost:44331/General/RolUsers/ActualizarUno";
        const string UrlActionPathDelete = "https://localhost:44331/General/RolUsers/BorrarUno?id={0}";

        // GET: RolUsers
        public async Task<ActionResult> Index()
        {
            rolUsuarios = new List<RolUsers>();
            responseClient = new Response();

            try
            {
                using (var client = new HttpClient())
                {
                    HttpResponseMessage response = await client.GetAsync(UrlActionPathList);
                    if (response.IsSuccessStatusCode)
                    {
                        var str = await response.Content.ReadAsStringAsync();
                        responseClient = JsonConvert.DeserializeObject<Response>(str);
                    }
                    if (responseClient.Success)
                    {
                        rolUsuarios = JsonConvert.DeserializeObject<List<RolUsers>>(responseClient.Value.ToString());
                    }
                }
            }
            catch (Exception error)
            {
                ViewBag.ErrorInfo = ERRORMESSAGE;
                ViewBag.ErrorMessage = error.Message;
                ViewBag.InnerException = error.InnerException;
                ViewBag.StackTrace = error.StackTrace;
                return View("Error");
            }
            return View(rolUsuarios);
        }

        // GET: RolUsers/Details/5
        public async Task<ActionResult> Details(int id)
        {
            rolUsuario = new RolUsers();
            responseClient = new Response();
            try
            {
                using (var client = new HttpClient())
                {
                    HttpResponseMessage response = await client.GetAsync(string.Format(UrlActionPathDetails, id));
                    if (response.IsSuccessStatusCode)
                    {
                        var str = await response.Content.ReadAsStringAsync();
                        responseClient = JsonConvert.DeserializeObject<Response>(str);
                    }
                    if (responseClient.Success)
                    {
                        rolUsuario = JsonConvert.DeserializeObject<RolUsers>(responseClient.Value.ToString());
                    }
                }
            }
            catch (Exception error)
            {
                ViewBag.ErrorInfo = ERRORMESSAGE;
                ViewBag.ErrorMessage = error.Message;
                ViewBag.InnerException = error.InnerException;
                ViewBag.StackTrace = error.StackTrace;
                return View("Error");
            }
            return View(rolUsuario);
        }

        // GET: RolUsers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RolUsers/Create
        [HttpPost]
        public async Task<ActionResult> Create(RolUsers collection)
        {
            try
            {
                responseClient = new Response();

                using (var client = new HttpClient())
                {
                    var json = JsonConvert.SerializeObject(collection);
                    var stringContent = new StringContent(json, Encoding.UTF8, "application/json");

                    HttpResponseMessage response = await client.PostAsync(UrlActionPathInsertOne, stringContent);

                    string resultContent = response.Content.ReadAsStringAsync().Result;

                }

                return RedirectToAction("Index");
            }
            catch (Exception error)
            {
                ViewBag.ErrorInfo = ERRORMESSAGE;
                ViewBag.ErrorMessage = error.Message;
                ViewBag.InnerException = error.InnerException;
                ViewBag.StackTrace = error.StackTrace;
                return View("Error");
            }
        }

        // GET: RolUsers/Edit/5
        public async Task< ActionResult> Edit(int id)
        {
            rolUsuario = new RolUsers();
            responseClient = new Response();

            try
            {
                using (var client = new HttpClient())
                {
                    HttpResponseMessage response = await client.GetAsync(string.Format(UrlActionPathDetails, id));
                    if (response.IsSuccessStatusCode)
                    {
                        var str = await response.Content.ReadAsStringAsync();
                        responseClient = JsonConvert.DeserializeObject<Response>(str);
                    }
                    if (responseClient.Success)
                    {
                        rolUsuario = JsonConvert.DeserializeObject<RolUsers>(responseClient.Value.ToString());
                    }
                }
            }
            catch (Exception error)
            {
                ViewBag.ErrorInfo = ERRORMESSAGE;
                ViewBag.ErrorMessage = error.Message;
                ViewBag.InnerException = error.InnerException;
                ViewBag.StackTrace = error.StackTrace;
                return View("Error");
            }
            return View(rolUsuario);
        }

        // POST: RolUsers/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(int id, RolUsers collection)
        {
            try
            {
                responseClient = new Response();

                using (var client = new HttpClient())
                {
                    var json = JsonConvert.SerializeObject(collection);
                    var stringContent = new StringContent(json, Encoding.UTF8, "application/json");

                    HttpResponseMessage response = await client.PutAsync(UrlActionPathUpdate, stringContent);

                    string resultContent = response.Content.ReadAsStringAsync().Result;

                }

                return RedirectToAction("Index");
            }
            catch (Exception error)
            {
                ViewBag.ErrorInfo = ERRORMESSAGE;
                ViewBag.ErrorMessage = error.Message;
                ViewBag.InnerException = error.InnerException;
                ViewBag.StackTrace = error.StackTrace;
                return View("Error");
            }
        }

        // GET: RolUsers/Delete/5
        public async Task< ActionResult> Delete(int id)
        {
            rolUsuario = new RolUsers();
            responseClient = new Response();

            try
            {
                using (var client = new HttpClient())
                {
                    HttpResponseMessage response = await client.GetAsync(string.Format(UrlActionPathDetails, id));
                    if (response.IsSuccessStatusCode)
                    {
                        var str = await response.Content.ReadAsStringAsync();
                        responseClient = JsonConvert.DeserializeObject<Response>(str);
                    }
                    if (responseClient.Success)
                    {
                        rolUsuario = JsonConvert.DeserializeObject<RolUsers>(responseClient.Value.ToString());
                    }
                }
            }
            catch (Exception error)
            {
                ViewBag.ErrorInfo = ERRORMESSAGE;
                ViewBag.ErrorMessage = error.Message;
                ViewBag.InnerException = error.InnerException;
                ViewBag.StackTrace = error.StackTrace;
                return View("Error");
            }
            return View(rolUsuario);
        }

        // POST: RolUsers/Delete/5
        [HttpPost]
        public async Task<ActionResult> Delete(int id, RolUsers collection)
        {
            try
            {
                responseClient = new Response();

                using (var client = new HttpClient())
                {
                    var json = JsonConvert.SerializeObject(collection);
                    var stringContent = new StringContent(json, Encoding.UTF8, "application/json");

                    HttpResponseMessage response = await client.DeleteAsync(string.Format(UrlActionPathDetails, id));

                    string resultContent = response.Content.ReadAsStringAsync().Result;

                }

                return RedirectToAction("Index");
            }
            catch (Exception error)
            {
                ViewBag.ErrorInfo = ERRORMESSAGE;
                ViewBag.ErrorMessage = error.Message;
                ViewBag.InnerException = error.InnerException;
                ViewBag.StackTrace = error.StackTrace;
                return View("Error");
            }
        }
    }
}

Asp.ErpFidelitas.General.v2/Views/RolUsers/Create.cshtml
@model Asp.ErpFidelitas.General.v2.Entities.RolUsers

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "RolUsers", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RolUsers</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RolId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RolId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RolId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeRol, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TypeRol, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.TypeRol, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Asp.ErpFidelitas.General.v2/Views/RolUsers/Delete.cshtml
@model Asp.ErpFidelitas.General.v2.Entities.RolUsers

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RolUsers</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RolId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RolId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeRol)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeRol)
        </dd>

    </dl>

    @using (Html.BeginForm("Delete", "RolUsers", FormMethod.Post)) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Asp.ErpFidelitas.General.v2/Views/RolUsers/Details.cshtml
@model Asp.ErpFidelitas.General.v2.Entities.RolUsers

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>RolUsers</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RolId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RolId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeRol)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeRol)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new {id = Model.RolId}) |
    @Html.ActionLink("Back to List", "Index")
</p>

Asp.ErpFidelitas.General.v2/Views/RolUsers/Edit.cshtml
@model Asp.ErpFidelitas.General.v2.Entities.RolUsers

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "RolUsers", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RolUsers</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RolId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RolId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RolId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeRol, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TypeRol, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TypeRol, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Asp.ErpFidelitas.General.v2/Views/RolUsers/Index.cshtml
@model IEnumerable<Asp.ErpFidelitas.General.v2.Entities.RolUsers>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RolId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TypeRol)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RolId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TypeRol)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.RolId }) |
            @Html.ActionLink("Details", "Details", new {  id=item.RolId  }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.RolId  })
        </td>
    </tr>
}

</table>